apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 3
    template:
      metadata:
        labels:
          name: auth
      spec:
        containers:
          - name: auth
            image: akguy/auth_test
            ports:
              - containerPorts: 5000
            envFrom:
              - configMapRef: 
                  name: auth-configmap
              - secretRef:
                  name: auth-secret
            
        
